package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

// runGenCompose writes a docker-compose.yml and a matching RotomNG dev config
// that together stand up a full local test environment:
//
//   - rotom-ng:       the backend, built from the repo Dockerfile with the
//     DEV_MODE build arg (unminified, embedded dev UI).
//   - ui-dev:         a Vite dev server mounting the repo source for live,
//     no-build UI editing with hot reload.
//   - mock-connector: a simulated fleet driving real connections in.
func runGenCompose(args []string) error {
	fs := flag.NewFlagSet("gen-compose", flag.ExitOnError)

	var (
		outDir      string
		devices     int
		workers     int
		controllers int
		rpcInterval string
		force       bool
	)
	fs.StringVar(&outDir, "out", ".", "output directory for docker-compose.yml and configs/")
	fs.IntVar(&devices, "devices", 3, "devices the mock-connector service simulates")
	fs.IntVar(&workers, "workers", 2, "workers per device the mock-connector service simulates")
	fs.IntVar(&controllers, "controllers", 4, "controllers the mock-connector service simulates")
	fs.StringVar(&rpcInterval, "rpc-interval", "10s", "RPC interval for the mock-connector service")
	fs.BoolVar(&force, "force", false, "overwrite existing files")

	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}

	composePath := filepath.Join(outDir, "docker-compose.yml")
	configDir := filepath.Join(outDir, "configs")
	configPath := filepath.Join(configDir, "rotom-ng.toml")

	if err := os.MkdirAll(configDir, 0o750); err != nil {
		return fmt.Errorf("create configs dir: %w", err)
	}

	compose := fmt.Sprintf(composeTemplate, devices, workers, controllers, rpcInterval)
	if err := writeFile(composePath, compose, force); err != nil {
		return err
	}
	if err := writeFile(configPath, configTemplate, force); err != nil {
		return err
	}

	fmt.Fprintf(os.Stdout, "Wrote %s\n", composePath)
	fmt.Fprintf(os.Stdout, "Wrote %s\n", configPath)
	fmt.Fprintf(os.Stdout, "\nNext steps:\n")
	fmt.Fprintf(os.Stdout, "  cd %s\n", outDir)
	fmt.Fprintf(os.Stdout, "  docker compose up --build\n\n")
	fmt.Fprintf(os.Stdout, "Then open:\n")
	fmt.Fprintf(os.Stdout, "  http://localhost:4201   live UI (Vite dev server, hot reload from source)\n")
	fmt.Fprintf(os.Stdout, "  http://localhost:7072   backend API + embedded dev UI\n")
	return nil
}

// writeFile writes content to path, refusing to overwrite unless force is set.
func writeFile(path, content string, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists (use -force to overwrite)", path)
		}
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// composeTemplate has four %d/%s verbs: devices, workers, controllers, rpc-interval.
const composeTemplate = `# Generated by: rotom-ng-mock-connector gen-compose
#
# Local RotomNG dev + test stack:
#   rotom-ng        backend built in DEV_MODE (unminified embedded UI)
#   ui-dev          Vite dev server with hot reload from mounted source
#   mock-connector  simulated fleet of devices, workers, and controllers
#
# Paths are relative to apps/rotom-ng-mock-connector/. The build context is the
# repo root (../..). Run "docker compose up --build" from this directory.
services:
  rotom-ng:
    build:
      context: ../..
      dockerfile: apps/rotom-ng/Dockerfile
      args:
        DEV_MODE: "true"
    container_name: rotom-ng-dev
    command: ["./rotom-ng", "configs/rotom-ng.toml"]
    restart: unless-stopped
    volumes:
      - ./configs:/rotom-ng/configs
    ports:
      - "7070:7070"   # device listener (devices + workers)
      - "7071:7071"   # controller listener
      - "7072:7072"   # http api + embedded UI
      - "4201:4201"   # vite dev server (served by ui-dev via shared netns)

  # Live UI dev server: mounts the repo and runs Vite directly from source, so
  # edits under apps/rotom-ng-ui/ or libs/base-ui/ hot-reload with no rebuild.
  # Shares rotom-ng's network namespace so Vite's built-in /api proxy
  # (-> localhost:7072) reaches the backend, and 4201 is published above.
  ui-dev:
    image: oven/bun:1-alpine
    working_dir: /app
    network_mode: "service:rotom-ng"
    depends_on:
      - rotom-ng
    volumes:
      - ../..:/app
    command: sh -c "bun install --frozen-lockfile && bun run dev"

  # Simulated fleet. Runs the mock connector straight from source with "go run"
  # and points it at the backend over the compose network.
  mock-connector:
    image: golang:1.26-alpine
    working_dir: /app
    depends_on:
      - rotom-ng
    volumes:
      - ../..:/app
      - mock-go-cache:/go/pkg/mod
    command:
      - go
      - run
      - ./apps/rotom-ng-mock-connector
      - -device-endpoint=ws://rotom-ng:7070
      - -controller-endpoint=ws://rotom-ng:7071
      - -devices=%d
      - -workers=%d
      - -controllers=%d
      - -rpc-interval=%s

volumes:
  mock-go-cache:
`

// configTemplate is a minimal RotomNG dev config with debug logging to stdout.
const configTemplate = `# Generated by: rotom-ng-mock-connector gen-compose
instance = "rotom-ng-dev"

[device_listener]
address = ":7070"
# secret = ""   # if set, pass the same value to the connector via -device-secret

[controller_listener]
address = ":7071"
# secret = ""   # if set, pass the same value to the connector via -controller-secret

[http_listener]
address = ":7072"
# secret = ""

[logging]
level = "debug"
format = "plain"

[logging.file]
disable = true

[prometheus]
enable = true
`
