//RotomProtos V2

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rotom.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthStatus int32

const (
	AuthStatus_AUTH_STATUS_UNSET                     AuthStatus = 0
	AuthStatus_AUTH_STATUS_AUTH_TOKEN_REQUEST_FAILED AuthStatus = 1
	AuthStatus_AUTH_STATUS_AUTH_TOKEN_REQUESTED      AuthStatus = 2
	AuthStatus_AUTH_STATUS_GOT_AUTH_TOKEN            AuthStatus = 3
	AuthStatus_AUTH_STATUS_DEVICE_INCOMPATIBLE       AuthStatus = 4
	AuthStatus_AUTH_STATUS_USER_NOT_FOUND            AuthStatus = 5
	AuthStatus_AUTH_STATUS_ACCESS_DENIED             AuthStatus = 6
	AuthStatus_AUTH_STATUS_ACCESS_SUSPENDED          AuthStatus = 7
	AuthStatus_AUTH_STATUS_ACCESS_RATE_LIMITED       AuthStatus = 8
	AuthStatus_AUTH_STATUS_SESSION_TERMINATED        AuthStatus = 9
	AuthStatus_AUTH_STATUS_SESSION_FAILED            AuthStatus = 10
	AuthStatus_AUTH_STATUS_LOGIN_TIMEOUT             AuthStatus = 20
)

// Enum value maps for AuthStatus.
var (
	AuthStatus_name = map[int32]string{
		0:  "AUTH_STATUS_UNSET",
		1:  "AUTH_STATUS_AUTH_TOKEN_REQUEST_FAILED",
		2:  "AUTH_STATUS_AUTH_TOKEN_REQUESTED",
		3:  "AUTH_STATUS_GOT_AUTH_TOKEN",
		4:  "AUTH_STATUS_DEVICE_INCOMPATIBLE",
		5:  "AUTH_STATUS_USER_NOT_FOUND",
		6:  "AUTH_STATUS_ACCESS_DENIED",
		7:  "AUTH_STATUS_ACCESS_SUSPENDED",
		8:  "AUTH_STATUS_ACCESS_RATE_LIMITED",
		9:  "AUTH_STATUS_SESSION_TERMINATED",
		10: "AUTH_STATUS_SESSION_FAILED",
		20: "AUTH_STATUS_LOGIN_TIMEOUT",
	}
	AuthStatus_value = map[string]int32{
		"AUTH_STATUS_UNSET":                     0,
		"AUTH_STATUS_AUTH_TOKEN_REQUEST_FAILED": 1,
		"AUTH_STATUS_AUTH_TOKEN_REQUESTED":      2,
		"AUTH_STATUS_GOT_AUTH_TOKEN":            3,
		"AUTH_STATUS_DEVICE_INCOMPATIBLE":       4,
		"AUTH_STATUS_USER_NOT_FOUND":            5,
		"AUTH_STATUS_ACCESS_DENIED":             6,
		"AUTH_STATUS_ACCESS_SUSPENDED":          7,
		"AUTH_STATUS_ACCESS_RATE_LIMITED":       8,
		"AUTH_STATUS_SESSION_TERMINATED":        9,
		"AUTH_STATUS_SESSION_FAILED":            10,
		"AUTH_STATUS_LOGIN_TIMEOUT":             20,
	}
)

func (x AuthStatus) Enum() *AuthStatus {
	p := new(AuthStatus)
	*p = x
	return p
}

func (x AuthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rotom_proto_enumTypes[0].Descriptor()
}

func (AuthStatus) Type() protoreflect.EnumType {
	return &file_rotom_proto_enumTypes[0]
}

func (x AuthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthStatus.Descriptor instead.
func (AuthStatus) EnumDescriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{0}
}

type RpcStatus int32

const (
	RpcStatus_RPC_STATUS_UNDEFINED               RpcStatus = 0
	RpcStatus_RPC_STATUS_SUCCESS                 RpcStatus = 1
	RpcStatus_RPC_STATUS_BAD_RESPONSE            RpcStatus = 3
	RpcStatus_RPC_STATUS_ACTION_ERROR            RpcStatus = 4
	RpcStatus_RPC_STATUS_DISPATCH_ERROR          RpcStatus = 5
	RpcStatus_RPC_STATUS_SERVER_ERROR            RpcStatus = 6
	RpcStatus_RPC_STATUS_ASSIGNMENT_ERROR        RpcStatus = 7
	RpcStatus_RPC_STATUS_PROTOCOL_ERROR          RpcStatus = 8
	RpcStatus_RPC_STATUS_AUTHENTICATION_ERROR    RpcStatus = 9
	RpcStatus_RPC_STATUS_CANCELLED_REQUEST       RpcStatus = 10
	RpcStatus_RPC_STATUS_UNKNOWN_ERROR           RpcStatus = 11
	RpcStatus_RPC_STATUS_NO_RETRIES_ERROR        RpcStatus = 12
	RpcStatus_RPC_STATUS_UNAUTHORIZED_ERROR      RpcStatus = 13
	RpcStatus_RPC_STATUS_PARSING_ERROR           RpcStatus = 14
	RpcStatus_RPC_STATUS_ACCESS_DENIED           RpcStatus = 15
	RpcStatus_RPC_STATUS_ACCESS_SUSPENDED        RpcStatus = 16
	RpcStatus_RPC_STATUS_DEVICE_INCOMPATIBLE     RpcStatus = 17
	RpcStatus_RPC_STATUS_ACCESS_RATE_LIMITED     RpcStatus = 18
	RpcStatus_RPC_STATUS_GOOGLE_PLAY_NOT_READY   RpcStatus = 19
	RpcStatus_RPC_STATUS_LOGIN_ERROR_BAIL        RpcStatus = 20
	RpcStatus_RPC_STATUS_MITM_DISALLOWED_REQUEST RpcStatus = 99
)

// Enum value maps for RpcStatus.
var (
	RpcStatus_name = map[int32]string{
		0:  "RPC_STATUS_UNDEFINED",
		1:  "RPC_STATUS_SUCCESS",
		3:  "RPC_STATUS_BAD_RESPONSE",
		4:  "RPC_STATUS_ACTION_ERROR",
		5:  "RPC_STATUS_DISPATCH_ERROR",
		6:  "RPC_STATUS_SERVER_ERROR",
		7:  "RPC_STATUS_ASSIGNMENT_ERROR",
		8:  "RPC_STATUS_PROTOCOL_ERROR",
		9:  "RPC_STATUS_AUTHENTICATION_ERROR",
		10: "RPC_STATUS_CANCELLED_REQUEST",
		11: "RPC_STATUS_UNKNOWN_ERROR",
		12: "RPC_STATUS_NO_RETRIES_ERROR",
		13: "RPC_STATUS_UNAUTHORIZED_ERROR",
		14: "RPC_STATUS_PARSING_ERROR",
		15: "RPC_STATUS_ACCESS_DENIED",
		16: "RPC_STATUS_ACCESS_SUSPENDED",
		17: "RPC_STATUS_DEVICE_INCOMPATIBLE",
		18: "RPC_STATUS_ACCESS_RATE_LIMITED",
		19: "RPC_STATUS_GOOGLE_PLAY_NOT_READY",
		20: "RPC_STATUS_LOGIN_ERROR_BAIL",
		99: "RPC_STATUS_MITM_DISALLOWED_REQUEST",
	}
	RpcStatus_value = map[string]int32{
		"RPC_STATUS_UNDEFINED":               0,
		"RPC_STATUS_SUCCESS":                 1,
		"RPC_STATUS_BAD_RESPONSE":            3,
		"RPC_STATUS_ACTION_ERROR":            4,
		"RPC_STATUS_DISPATCH_ERROR":          5,
		"RPC_STATUS_SERVER_ERROR":            6,
		"RPC_STATUS_ASSIGNMENT_ERROR":        7,
		"RPC_STATUS_PROTOCOL_ERROR":          8,
		"RPC_STATUS_AUTHENTICATION_ERROR":    9,
		"RPC_STATUS_CANCELLED_REQUEST":       10,
		"RPC_STATUS_UNKNOWN_ERROR":           11,
		"RPC_STATUS_NO_RETRIES_ERROR":        12,
		"RPC_STATUS_UNAUTHORIZED_ERROR":      13,
		"RPC_STATUS_PARSING_ERROR":           14,
		"RPC_STATUS_ACCESS_DENIED":           15,
		"RPC_STATUS_ACCESS_SUSPENDED":        16,
		"RPC_STATUS_DEVICE_INCOMPATIBLE":     17,
		"RPC_STATUS_ACCESS_RATE_LIMITED":     18,
		"RPC_STATUS_GOOGLE_PLAY_NOT_READY":   19,
		"RPC_STATUS_LOGIN_ERROR_BAIL":        20,
		"RPC_STATUS_MITM_DISALLOWED_REQUEST": 99,
	}
)

func (x RpcStatus) Enum() *RpcStatus {
	p := new(RpcStatus)
	*p = x
	return p
}

func (x RpcStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rotom_proto_enumTypes[1].Descriptor()
}

func (RpcStatus) Type() protoreflect.EnumType {
	return &file_rotom_proto_enumTypes[1]
}

func (x RpcStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcStatus.Descriptor instead.
func (RpcStatus) EnumDescriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{1}
}

type MitmRequest_Method int32

const (
	MitmRequest_UNSET       MitmRequest_Method = 0
	MitmRequest_LOGIN       MitmRequest_Method = 1
	MitmRequest_RPC_REQUEST MitmRequest_Method = 2
)

// Enum value maps for MitmRequest_Method.
var (
	MitmRequest_Method_name = map[int32]string{
		0: "UNSET",
		1: "LOGIN",
		2: "RPC_REQUEST",
	}
	MitmRequest_Method_value = map[string]int32{
		"UNSET":       0,
		"LOGIN":       1,
		"RPC_REQUEST": 2,
	}
)

func (x MitmRequest_Method) Enum() *MitmRequest_Method {
	p := new(MitmRequest_Method)
	*p = x
	return p
}

func (x MitmRequest_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MitmRequest_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_rotom_proto_enumTypes[2].Descriptor()
}

func (MitmRequest_Method) Type() protoreflect.EnumType {
	return &file_rotom_proto_enumTypes[2]
}

func (x MitmRequest_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MitmRequest_Method.Descriptor instead.
func (MitmRequest_Method) EnumDescriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{0, 0}
}

type MitmRequest_LoginRequest_LoginSource int32

const (
	MitmRequest_LoginRequest_UNSET MitmRequest_LoginRequest_LoginSource = 0
	// Deprecated: Marked as deprecated in rotom.proto.
	MitmRequest_LoginRequest_PTC       MitmRequest_LoginRequest_LoginSource = 1
	MitmRequest_LoginRequest_PTC_OAUTH MitmRequest_LoginRequest_LoginSource = 2
	MitmRequest_LoginRequest_FB        MitmRequest_LoginRequest_LoginSource = 3
	MitmRequest_LoginRequest_GOOGLE    MitmRequest_LoginRequest_LoginSource = 4
	// Deprecated: Marked as deprecated in rotom.proto.
	MitmRequest_LoginRequest_SUPER_AWESOME MitmRequest_LoginRequest_LoginSource = 5
	MitmRequest_LoginRequest_NIANTIC_JWT   MitmRequest_LoginRequest_LoginSource = 6
)

// Enum value maps for MitmRequest_LoginRequest_LoginSource.
var (
	MitmRequest_LoginRequest_LoginSource_name = map[int32]string{
		0: "UNSET",
		1: "PTC",
		2: "PTC_OAUTH",
		3: "FB",
		4: "GOOGLE",
		5: "SUPER_AWESOME",
		6: "NIANTIC_JWT",
	}
	MitmRequest_LoginRequest_LoginSource_value = map[string]int32{
		"UNSET":         0,
		"PTC":           1,
		"PTC_OAUTH":     2,
		"FB":            3,
		"GOOGLE":        4,
		"SUPER_AWESOME": 5,
		"NIANTIC_JWT":   6,
	}
)

func (x MitmRequest_LoginRequest_LoginSource) Enum() *MitmRequest_LoginRequest_LoginSource {
	p := new(MitmRequest_LoginRequest_LoginSource)
	*p = x
	return p
}

func (x MitmRequest_LoginRequest_LoginSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MitmRequest_LoginRequest_LoginSource) Descriptor() protoreflect.EnumDescriptor {
	return file_rotom_proto_enumTypes[3].Descriptor()
}

func (MitmRequest_LoginRequest_LoginSource) Type() protoreflect.EnumType {
	return &file_rotom_proto_enumTypes[3]
}

func (x MitmRequest_LoginRequest_LoginSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MitmRequest_LoginRequest_LoginSource.Descriptor instead.
func (MitmRequest_LoginRequest_LoginSource) EnumDescriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{0, 0, 0}
}

type MitmResponse_Status int32

const (
	MitmResponse_UNSET                 MitmResponse_Status = 0
	MitmResponse_SUCCESS               MitmResponse_Status = 200
	MitmResponse_ERROR_UNKNOWN         MitmResponse_Status = 500
	MitmResponse_ERROR_RETRY_LATER     MitmResponse_Status = 501
	MitmResponse_ERROR_WORKER_STOPPED  MitmResponse_Status = 502
	MitmResponse_ERROR_RECONNECT       MitmResponse_Status = 503
	MitmResponse_ERROR_RESTART_SESSION MitmResponse_Status = 504
)

// Enum value maps for MitmResponse_Status.
var (
	MitmResponse_Status_name = map[int32]string{
		0:   "UNSET",
		200: "SUCCESS",
		500: "ERROR_UNKNOWN",
		501: "ERROR_RETRY_LATER",
		502: "ERROR_WORKER_STOPPED",
		503: "ERROR_RECONNECT",
		504: "ERROR_RESTART_SESSION",
	}
	MitmResponse_Status_value = map[string]int32{
		"UNSET":                 0,
		"SUCCESS":               200,
		"ERROR_UNKNOWN":         500,
		"ERROR_RETRY_LATER":     501,
		"ERROR_WORKER_STOPPED":  502,
		"ERROR_RECONNECT":       503,
		"ERROR_RESTART_SESSION": 504,
	}
)

func (x MitmResponse_Status) Enum() *MitmResponse_Status {
	p := new(MitmResponse_Status)
	*p = x
	return p
}

func (x MitmResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MitmResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_rotom_proto_enumTypes[4].Descriptor()
}

func (MitmResponse_Status) Type() protoreflect.EnumType {
	return &file_rotom_proto_enumTypes[4]
}

func (x MitmResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MitmResponse_Status.Descriptor instead.
func (MitmResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{1, 0}
}

type WelcomeMessage_Platform int32

const (
	WelcomeMessage_UNSET   WelcomeMessage_Platform = 0
	WelcomeMessage_IOS     WelcomeMessage_Platform = 1
	WelcomeMessage_ANDROID WelcomeMessage_Platform = 2
)

// Enum value maps for WelcomeMessage_Platform.
var (
	WelcomeMessage_Platform_name = map[int32]string{
		0: "UNSET",
		1: "IOS",
		2: "ANDROID",
	}
	WelcomeMessage_Platform_value = map[string]int32{
		"UNSET":   0,
		"IOS":     1,
		"ANDROID": 2,
	}
)

func (x WelcomeMessage_Platform) Enum() *WelcomeMessage_Platform {
	p := new(WelcomeMessage_Platform)
	*p = x
	return p
}

func (x WelcomeMessage_Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WelcomeMessage_Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_rotom_proto_enumTypes[5].Descriptor()
}

func (WelcomeMessage_Platform) Type() protoreflect.EnumType {
	return &file_rotom_proto_enumTypes[5]
}

func (x WelcomeMessage_Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WelcomeMessage_Platform.Descriptor instead.
func (WelcomeMessage_Platform) EnumDescriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{2, 0}
}

type RegisterControllerResponse_RegisterControllerResponseStatus int32

const (
	RegisterControllerResponse_UNSET                RegisterControllerResponse_RegisterControllerResponseStatus = 0
	RegisterControllerResponse_SUCCESS              RegisterControllerResponse_RegisterControllerResponseStatus = 1
	RegisterControllerResponse_NO_WORKERS_AVAILABLE RegisterControllerResponse_RegisterControllerResponseStatus = 2
	RegisterControllerResponse_ERROR                RegisterControllerResponse_RegisterControllerResponseStatus = 3
)

// Enum value maps for RegisterControllerResponse_RegisterControllerResponseStatus.
var (
	RegisterControllerResponse_RegisterControllerResponseStatus_name = map[int32]string{
		0: "UNSET",
		1: "SUCCESS",
		2: "NO_WORKERS_AVAILABLE",
		3: "ERROR",
	}
	RegisterControllerResponse_RegisterControllerResponseStatus_value = map[string]int32{
		"UNSET":                0,
		"SUCCESS":              1,
		"NO_WORKERS_AVAILABLE": 2,
		"ERROR":                3,
	}
)

func (x RegisterControllerResponse_RegisterControllerResponseStatus) Enum() *RegisterControllerResponse_RegisterControllerResponseStatus {
	p := new(RegisterControllerResponse_RegisterControllerResponseStatus)
	*p = x
	return p
}

func (x RegisterControllerResponse_RegisterControllerResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterControllerResponse_RegisterControllerResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rotom_proto_enumTypes[6].Descriptor()
}

func (RegisterControllerResponse_RegisterControllerResponseStatus) Type() protoreflect.EnumType {
	return &file_rotom_proto_enumTypes[6]
}

func (x RegisterControllerResponse_RegisterControllerResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterControllerResponse_RegisterControllerResponseStatus.Descriptor instead.
func (RegisterControllerResponse_RegisterControllerResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{4, 0}
}

type MitmRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method MitmRequest_Method     `protobuf:"varint,2,opt,name=method,proto3,enum=RotomProtos.MitmRequest_Method" json:"method,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MitmRequest_LoginRequest_
	//	*MitmRequest_RpcRequest_
	Payload       isMitmRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MitmRequest) Reset() {
	*x = MitmRequest{}
	mi := &file_rotom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitmRequest) ProtoMessage() {}

func (x *MitmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitmRequest.ProtoReflect.Descriptor instead.
func (*MitmRequest) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{0}
}

func (x *MitmRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MitmRequest) GetMethod() MitmRequest_Method {
	if x != nil {
		return x.Method
	}
	return MitmRequest_UNSET
}

func (x *MitmRequest) GetPayload() isMitmRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MitmRequest) GetLoginRequest() *MitmRequest_LoginRequest {
	if x != nil {
		if x, ok := x.Payload.(*MitmRequest_LoginRequest_); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *MitmRequest) GetRpcRequest() *MitmRequest_RpcRequest {
	if x != nil {
		if x, ok := x.Payload.(*MitmRequest_RpcRequest_); ok {
			return x.RpcRequest
		}
	}
	return nil
}

type isMitmRequest_Payload interface {
	isMitmRequest_Payload()
}

type MitmRequest_LoginRequest_ struct {
	LoginRequest *MitmRequest_LoginRequest `protobuf:"bytes,3,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type MitmRequest_RpcRequest_ struct {
	RpcRequest *MitmRequest_RpcRequest `protobuf:"bytes,4,opt,name=rpc_request,json=rpcRequest,proto3,oneof"`
}

func (*MitmRequest_LoginRequest_) isMitmRequest_Payload() {}

func (*MitmRequest_RpcRequest_) isMitmRequest_Payload() {}

type MitmResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status MitmResponse_Status    `protobuf:"varint,2,opt,name=status,proto3,enum=RotomProtos.MitmResponse_Status" json:"status,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MitmResponse_LoginResponse_
	//	*MitmResponse_RpcResponse_
	Payload       isMitmResponse_Payload `protobuf_oneof:"payload"`
	MitmError     string                 `protobuf:"bytes,100,opt,name=mitm_error,json=mitmError,proto3" json:"mitm_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MitmResponse) Reset() {
	*x = MitmResponse{}
	mi := &file_rotom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitmResponse) ProtoMessage() {}

func (x *MitmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitmResponse.ProtoReflect.Descriptor instead.
func (*MitmResponse) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{1}
}

func (x *MitmResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MitmResponse) GetStatus() MitmResponse_Status {
	if x != nil {
		return x.Status
	}
	return MitmResponse_UNSET
}

func (x *MitmResponse) GetPayload() isMitmResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MitmResponse) GetLoginResponse() *MitmResponse_LoginResponse {
	if x != nil {
		if x, ok := x.Payload.(*MitmResponse_LoginResponse_); ok {
			return x.LoginResponse
		}
	}
	return nil
}

func (x *MitmResponse) GetRpcResponse() *MitmResponse_RpcResponse {
	if x != nil {
		if x, ok := x.Payload.(*MitmResponse_RpcResponse_); ok {
			return x.RpcResponse
		}
	}
	return nil
}

func (x *MitmResponse) GetMitmError() string {
	if x != nil {
		return x.MitmError
	}
	return ""
}

type isMitmResponse_Payload interface {
	isMitmResponse_Payload()
}

type MitmResponse_LoginResponse_ struct {
	LoginResponse *MitmResponse_LoginResponse `protobuf:"bytes,3,opt,name=login_response,json=loginResponse,proto3,oneof"`
}

type MitmResponse_RpcResponse_ struct {
	RpcResponse *MitmResponse_RpcResponse `protobuf:"bytes,4,opt,name=rpc_response,json=rpcResponse,proto3,oneof"`
}

func (*MitmResponse_LoginResponse_) isMitmResponse_Payload() {}

func (*MitmResponse_RpcResponse_) isMitmResponse_Payload() {}

type WelcomeMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	WorkerId      string                  `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Origin        string                  `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	VersionCode   int32                   `protobuf:"varint,3,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	VersionName   string                  `protobuf:"bytes,4,opt,name=version_name,json=versionName,proto3" json:"version_name,omitempty"`
	Useragent     string                  `protobuf:"bytes,5,opt,name=useragent,proto3" json:"useragent,omitempty"`
	DeviceId      string                  `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform      WelcomeMessage_Platform `protobuf:"varint,7,opt,name=platform,proto3,enum=RotomProtos.WelcomeMessage_Platform" json:"platform,omitempty"`
	Reserved1     bool                    `protobuf:"varint,8,opt,name=reserved1,proto3" json:"reserved1,omitempty"`
	Reserved2     string                  `protobuf:"bytes,9,opt,name=reserved2,proto3" json:"reserved2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeMessage) Reset() {
	*x = WelcomeMessage{}
	mi := &file_rotom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessage) ProtoMessage() {}

func (x *WelcomeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessage.ProtoReflect.Descriptor instead.
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{2}
}

func (x *WelcomeMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WelcomeMessage) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *WelcomeMessage) GetVersionCode() int32 {
	if x != nil {
		return x.VersionCode
	}
	return 0
}

func (x *WelcomeMessage) GetVersionName() string {
	if x != nil {
		return x.VersionName
	}
	return ""
}

func (x *WelcomeMessage) GetUseragent() string {
	if x != nil {
		return x.Useragent
	}
	return ""
}

func (x *WelcomeMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *WelcomeMessage) GetPlatform() WelcomeMessage_Platform {
	if x != nil {
		return x.Platform
	}
	return WelcomeMessage_UNSET
}

func (x *WelcomeMessage) GetReserved1() bool {
	if x != nil {
		return x.Reserved1
	}
	return false
}

func (x *WelcomeMessage) GetReserved2() string {
	if x != nil {
		return x.Reserved2
	}
	return ""
}

type RegisterControllerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProtoMajorVersion int32                  `protobuf:"varint,2,opt,name=proto_major_version,json=protoMajorVersion,proto3" json:"proto_major_version,omitempty"`
	ProtoMinorVersion int32                  `protobuf:"varint,3,opt,name=proto_minor_version,json=protoMinorVersion,proto3" json:"proto_minor_version,omitempty"`
	Weight            int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterControllerRequest) Reset() {
	*x = RegisterControllerRequest{}
	mi := &file_rotom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterControllerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterControllerRequest) ProtoMessage() {}

func (x *RegisterControllerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterControllerRequest.ProtoReflect.Descriptor instead.
func (*RegisterControllerRequest) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterControllerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterControllerRequest) GetProtoMajorVersion() int32 {
	if x != nil {
		return x.ProtoMajorVersion
	}
	return 0
}

func (x *RegisterControllerRequest) GetProtoMinorVersion() int32 {
	if x != nil {
		return x.ProtoMinorVersion
	}
	return 0
}

func (x *RegisterControllerRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type RegisterControllerResponse struct {
	state             protoimpl.MessageState                                      `protogen:"open.v1"`
	Status            RegisterControllerResponse_RegisterControllerResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=RotomProtos.RegisterControllerResponse_RegisterControllerResponseStatus" json:"status,omitempty"`
	StatusReason      string                                                      `protobuf:"bytes,2,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"`
	UserAgent         string                                                      `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ProtoMajorVersion int32                                                       `protobuf:"varint,4,opt,name=proto_major_version,json=protoMajorVersion,proto3" json:"proto_major_version,omitempty"`
	ProtoMinorVersion int32                                                       `protobuf:"varint,5,opt,name=proto_minor_version,json=protoMinorVersion,proto3" json:"proto_minor_version,omitempty"`
	AssignedWorkerId  string                                                      `protobuf:"bytes,7,opt,name=assigned_worker_id,json=assignedWorkerId,proto3" json:"assigned_worker_id,omitempty"`
	RetryAfter        int64                                                       `protobuf:"varint,8,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterControllerResponse) Reset() {
	*x = RegisterControllerResponse{}
	mi := &file_rotom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterControllerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterControllerResponse) ProtoMessage() {}

func (x *RegisterControllerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterControllerResponse.ProtoReflect.Descriptor instead.
func (*RegisterControllerResponse) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterControllerResponse) GetStatus() RegisterControllerResponse_RegisterControllerResponseStatus {
	if x != nil {
		return x.Status
	}
	return RegisterControllerResponse_UNSET
}

func (x *RegisterControllerResponse) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *RegisterControllerResponse) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RegisterControllerResponse) GetProtoMajorVersion() int32 {
	if x != nil {
		return x.ProtoMajorVersion
	}
	return 0
}

func (x *RegisterControllerResponse) GetProtoMinorVersion() int32 {
	if x != nil {
		return x.ProtoMinorVersion
	}
	return 0
}

func (x *RegisterControllerResponse) GetAssignedWorkerId() string {
	if x != nil {
		return x.AssignedWorkerId
	}
	return ""
}

func (x *RegisterControllerResponse) GetRetryAfter() int64 {
	if x != nil {
		return x.RetryAfter
	}
	return 0
}

type MitmRequest_LoginRequest struct {
	state             protoimpl.MessageState               `protogen:"open.v1"`
	Username          string                               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Source            MitmRequest_LoginRequest_LoginSource `protobuf:"varint,2,opt,name=source,proto3,enum=RotomProtos.MitmRequest_LoginRequest_LoginSource" json:"source,omitempty"`
	TokenProto        []byte                               `protobuf:"bytes,3,opt,name=token_proto,json=tokenProto,proto3" json:"token_proto,omitempty"`
	WorkerId          string                               `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	EnableCompression bool                                 `protobuf:"varint,5,opt,name=enable_compression,json=enableCompression,proto3" json:"enable_compression,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MitmRequest_LoginRequest) Reset() {
	*x = MitmRequest_LoginRequest{}
	mi := &file_rotom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitmRequest_LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitmRequest_LoginRequest) ProtoMessage() {}

func (x *MitmRequest_LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitmRequest_LoginRequest.ProtoReflect.Descriptor instead.
func (*MitmRequest_LoginRequest) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MitmRequest_LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MitmRequest_LoginRequest) GetSource() MitmRequest_LoginRequest_LoginSource {
	if x != nil {
		return x.Source
	}
	return MitmRequest_LoginRequest_UNSET
}

func (x *MitmRequest_LoginRequest) GetTokenProto() []byte {
	if x != nil {
		return x.TokenProto
	}
	return nil
}

func (x *MitmRequest_LoginRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *MitmRequest_LoginRequest) GetEnableCompression() bool {
	if x != nil {
		return x.EnableCompression
	}
	return false
}

type MitmRequest_RpcRequest struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Request       []*MitmRequest_RpcRequest_SingleRpcRequest `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
	Lat           float64                                    `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                                    `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MitmRequest_RpcRequest) Reset() {
	*x = MitmRequest_RpcRequest{}
	mi := &file_rotom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitmRequest_RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitmRequest_RpcRequest) ProtoMessage() {}

func (x *MitmRequest_RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitmRequest_RpcRequest.ProtoReflect.Descriptor instead.
func (*MitmRequest_RpcRequest) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MitmRequest_RpcRequest) GetRequest() []*MitmRequest_RpcRequest_SingleRpcRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *MitmRequest_RpcRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *MitmRequest_RpcRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type MitmRequest_RpcRequest_SingleRpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        int32                  `protobuf:"varint,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	IsCompressed  bool                   `protobuf:"varint,3,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MitmRequest_RpcRequest_SingleRpcRequest) Reset() {
	*x = MitmRequest_RpcRequest_SingleRpcRequest{}
	mi := &file_rotom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitmRequest_RpcRequest_SingleRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitmRequest_RpcRequest_SingleRpcRequest) ProtoMessage() {}

func (x *MitmRequest_RpcRequest_SingleRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitmRequest_RpcRequest_SingleRpcRequest.ProtoReflect.Descriptor instead.
func (*MitmRequest_RpcRequest_SingleRpcRequest) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *MitmRequest_RpcRequest_SingleRpcRequest) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *MitmRequest_RpcRequest_SingleRpcRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MitmRequest_RpcRequest_SingleRpcRequest) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

type MitmResponse_LoginResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WorkerId            string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status              AuthStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=RotomProtos.AuthStatus" json:"status,omitempty"`
	SupportsCompression bool                   `protobuf:"varint,3,opt,name=supports_compression,json=supportsCompression,proto3" json:"supports_compression,omitempty"`
	Useragent           string                 `protobuf:"bytes,4,opt,name=useragent,proto3" json:"useragent,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MitmResponse_LoginResponse) Reset() {
	*x = MitmResponse_LoginResponse{}
	mi := &file_rotom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitmResponse_LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitmResponse_LoginResponse) ProtoMessage() {}

func (x *MitmResponse_LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitmResponse_LoginResponse.ProtoReflect.Descriptor instead.
func (*MitmResponse_LoginResponse) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MitmResponse_LoginResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *MitmResponse_LoginResponse) GetStatus() AuthStatus {
	if x != nil {
		return x.Status
	}
	return AuthStatus_AUTH_STATUS_UNSET
}

func (x *MitmResponse_LoginResponse) GetSupportsCompression() bool {
	if x != nil {
		return x.SupportsCompression
	}
	return false
}

func (x *MitmResponse_LoginResponse) GetUseragent() string {
	if x != nil {
		return x.Useragent
	}
	return ""
}

type MitmResponse_RpcResponse struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	RpcStatus     RpcStatus                                     `protobuf:"varint,1,opt,name=rpc_status,json=rpcStatus,proto3,enum=RotomProtos.RpcStatus" json:"rpc_status,omitempty"`
	Response      []*MitmResponse_RpcResponse_SingleRpcResponse `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MitmResponse_RpcResponse) Reset() {
	*x = MitmResponse_RpcResponse{}
	mi := &file_rotom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitmResponse_RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitmResponse_RpcResponse) ProtoMessage() {}

func (x *MitmResponse_RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitmResponse_RpcResponse.ProtoReflect.Descriptor instead.
func (*MitmResponse_RpcResponse) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{1, 1}
}

func (x *MitmResponse_RpcResponse) GetRpcStatus() RpcStatus {
	if x != nil {
		return x.RpcStatus
	}
	return RpcStatus_RPC_STATUS_UNDEFINED
}

func (x *MitmResponse_RpcResponse) GetResponse() []*MitmResponse_RpcResponse_SingleRpcResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type MitmResponse_RpcResponse_SingleRpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        int32                  `protobuf:"varint,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	IsCompressed  bool                   `protobuf:"varint,3,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MitmResponse_RpcResponse_SingleRpcResponse) Reset() {
	*x = MitmResponse_RpcResponse_SingleRpcResponse{}
	mi := &file_rotom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitmResponse_RpcResponse_SingleRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitmResponse_RpcResponse_SingleRpcResponse) ProtoMessage() {}

func (x *MitmResponse_RpcResponse_SingleRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitmResponse_RpcResponse_SingleRpcResponse.ProtoReflect.Descriptor instead.
func (*MitmResponse_RpcResponse_SingleRpcResponse) Descriptor() ([]byte, []int) {
	return file_rotom_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *MitmResponse_RpcResponse_SingleRpcResponse) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *MitmResponse_RpcResponse_SingleRpcResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MitmResponse_RpcResponse_SingleRpcResponse) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

var File_rotom_proto protoreflect.FileDescriptor

const file_rotom_proto_rawDesc = "" +
	"\n" +
	"\vrotom.proto\x12\vRotomProtos\"\xed\x06\n" +
	"\vMitmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x127\n" +
	"\x06method\x18\x02 \x01(\x0e2\x1f.RotomProtos.MitmRequest.MethodR\x06method\x12L\n" +
	"\rlogin_request\x18\x03 \x01(\v2%.RotomProtos.MitmRequest.LoginRequestH\x00R\floginRequest\x12F\n" +
	"\vrpc_request\x18\x04 \x01(\v2#.RotomProtos.MitmRequest.RpcRequestH\x00R\n" +
	"rpcRequest\x1a\xd4\x02\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12I\n" +
	"\x06source\x18\x02 \x01(\x0e21.RotomProtos.MitmRequest.LoginRequest.LoginSourceR\x06source\x12\x1f\n" +
	"\vtoken_proto\x18\x03 \x01(\fR\n" +
	"tokenProto\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12-\n" +
	"\x12enable_compression\x18\x05 \x01(\bR\x11enableCompression\"p\n" +
	"\vLoginSource\x12\t\n" +
	"\x05UNSET\x10\x00\x12\v\n" +
	"\x03PTC\x10\x01\x1a\x02\b\x01\x12\r\n" +
	"\tPTC_OAUTH\x10\x02\x12\x06\n" +
	"\x02FB\x10\x03\x12\n" +
	"\n" +
	"\x06GOOGLE\x10\x04\x12\x15\n" +
	"\rSUPER_AWESOME\x10\x05\x1a\x02\b\x01\x12\x0f\n" +
	"\vNIANTIC_JWT\x10\x06\x1a\xeb\x01\n" +
	"\n" +
	"RpcRequest\x12N\n" +
	"\arequest\x18\x01 \x03(\v24.RotomProtos.MitmRequest.RpcRequest.SingleRpcRequestR\arequest\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x1ai\n" +
	"\x10SingleRpcRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\x05R\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12#\n" +
	"\ris_compressed\x18\x03 \x01(\bR\fisCompressed\"/\n" +
	"\x06Method\x12\t\n" +
	"\x05UNSET\x10\x00\x12\t\n" +
	"\x05LOGIN\x10\x01\x12\x0f\n" +
	"\vRPC_REQUEST\x10\x02B\t\n" +
	"\apayload\"\xf6\x06\n" +
	"\fMitmResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .RotomProtos.MitmResponse.StatusR\x06status\x12P\n" +
	"\x0elogin_response\x18\x03 \x01(\v2'.RotomProtos.MitmResponse.LoginResponseH\x00R\rloginResponse\x12J\n" +
	"\frpc_response\x18\x04 \x01(\v2%.RotomProtos.MitmResponse.RpcResponseH\x00R\vrpcResponse\x12\x1d\n" +
	"\n" +
	"mitm_error\x18d \x01(\tR\tmitmError\x1a\xae\x01\n" +
	"\rLoginResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.RotomProtos.AuthStatusR\x06status\x121\n" +
	"\x14supports_compression\x18\x03 \x01(\bR\x13supportsCompression\x12\x1c\n" +
	"\tuseragent\x18\x04 \x01(\tR\tuseragent\x1a\x85\x02\n" +
	"\vRpcResponse\x125\n" +
	"\n" +
	"rpc_status\x18\x01 \x01(\x0e2\x16.RotomProtos.RpcStatusR\trpcStatus\x12S\n" +
	"\bresponse\x18\x02 \x03(\v27.RotomProtos.MitmResponse.RpcResponse.SingleRpcResponseR\bresponse\x1aj\n" +
	"\x11SingleRpcResponse\x12\x16\n" +
	"\x06method\x18\x01 \x01(\x05R\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12#\n" +
	"\ris_compressed\x18\x03 \x01(\bR\fisCompressed\"\x9a\x01\n" +
	"\x06Status\x12\t\n" +
	"\x05UNSET\x10\x00\x12\f\n" +
	"\aSUCCESS\x10\xc8\x01\x12\x12\n" +
	"\rERROR_UNKNOWN\x10\xf4\x03\x12\x16\n" +
	"\x11ERROR_RETRY_LATER\x10\xf5\x03\x12\x19\n" +
	"\x14ERROR_WORKER_STOPPED\x10\xf6\x03\x12\x14\n" +
	"\x0fERROR_RECONNECT\x10\xf7\x03\x12\x1a\n" +
	"\x15ERROR_RESTART_SESSION\x10\xf8\x03B\t\n" +
	"\apayload\"\xf1\x02\n" +
	"\x0eWelcomeMessage\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12!\n" +
	"\fversion_code\x18\x03 \x01(\x05R\vversionCode\x12!\n" +
	"\fversion_name\x18\x04 \x01(\tR\vversionName\x12\x1c\n" +
	"\tuseragent\x18\x05 \x01(\tR\tuseragent\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12@\n" +
	"\bplatform\x18\a \x01(\x0e2$.RotomProtos.WelcomeMessage.PlatformR\bplatform\x12\x1c\n" +
	"\treserved1\x18\b \x01(\bR\treserved1\x12\x1c\n" +
	"\treserved2\x18\t \x01(\tR\treserved2\"+\n" +
	"\bPlatform\x12\t\n" +
	"\x05UNSET\x10\x00\x12\a\n" +
	"\x03IOS\x10\x01\x12\v\n" +
	"\aANDROID\x10\x02\"\xa3\x01\n" +
	"\x19RegisterControllerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13proto_major_version\x18\x02 \x01(\x05R\x11protoMajorVersion\x12.\n" +
	"\x13proto_minor_version\x18\x03 \x01(\x05R\x11protoMinorVersion\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\"\xd2\x03\n" +
	"\x1aRegisterControllerResponse\x12`\n" +
	"\x06status\x18\x01 \x01(\x0e2H.RotomProtos.RegisterControllerResponse.RegisterControllerResponseStatusR\x06status\x12#\n" +
	"\rstatus_reason\x18\x02 \x01(\tR\fstatusReason\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12.\n" +
	"\x13proto_major_version\x18\x04 \x01(\x05R\x11protoMajorVersion\x12.\n" +
	"\x13proto_minor_version\x18\x05 \x01(\x05R\x11protoMinorVersion\x12,\n" +
	"\x12assigned_worker_id\x18\a \x01(\tR\x10assignedWorkerId\x12\x1f\n" +
	"\vretry_after\x18\b \x01(\x03R\n" +
	"retryAfter\"_\n" +
	" RegisterControllerResponseStatus\x12\t\n" +
	"\x05UNSET\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x18\n" +
	"\x14NO_WORKERS_AVAILABLE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03*\xa2\x03\n" +
	"\n" +
	"AuthStatus\x12\x15\n" +
	"\x11AUTH_STATUS_UNSET\x10\x00\x12)\n" +
	"%AUTH_STATUS_AUTH_TOKEN_REQUEST_FAILED\x10\x01\x12$\n" +
	" AUTH_STATUS_AUTH_TOKEN_REQUESTED\x10\x02\x12\x1e\n" +
	"\x1aAUTH_STATUS_GOT_AUTH_TOKEN\x10\x03\x12#\n" +
	"\x1fAUTH_STATUS_DEVICE_INCOMPATIBLE\x10\x04\x12\x1e\n" +
	"\x1aAUTH_STATUS_USER_NOT_FOUND\x10\x05\x12\x1d\n" +
	"\x19AUTH_STATUS_ACCESS_DENIED\x10\x06\x12 \n" +
	"\x1cAUTH_STATUS_ACCESS_SUSPENDED\x10\a\x12#\n" +
	"\x1fAUTH_STATUS_ACCESS_RATE_LIMITED\x10\b\x12\"\n" +
	"\x1eAUTH_STATUS_SESSION_TERMINATED\x10\t\x12\x1e\n" +
	"\x1aAUTH_STATUS_SESSION_FAILED\x10\n" +
	"\x12\x1d\n" +
	"\x19AUTH_STATUS_LOGIN_TIMEOUT\x10\x14*\xb0\x05\n" +
	"\tRpcStatus\x12\x18\n" +
	"\x14RPC_STATUS_UNDEFINED\x10\x00\x12\x16\n" +
	"\x12RPC_STATUS_SUCCESS\x10\x01\x12\x1b\n" +
	"\x17RPC_STATUS_BAD_RESPONSE\x10\x03\x12\x1b\n" +
	"\x17RPC_STATUS_ACTION_ERROR\x10\x04\x12\x1d\n" +
	"\x19RPC_STATUS_DISPATCH_ERROR\x10\x05\x12\x1b\n" +
	"\x17RPC_STATUS_SERVER_ERROR\x10\x06\x12\x1f\n" +
	"\x1bRPC_STATUS_ASSIGNMENT_ERROR\x10\a\x12\x1d\n" +
	"\x19RPC_STATUS_PROTOCOL_ERROR\x10\b\x12#\n" +
	"\x1fRPC_STATUS_AUTHENTICATION_ERROR\x10\t\x12 \n" +
	"\x1cRPC_STATUS_CANCELLED_REQUEST\x10\n" +
	"\x12\x1c\n" +
	"\x18RPC_STATUS_UNKNOWN_ERROR\x10\v\x12\x1f\n" +
	"\x1bRPC_STATUS_NO_RETRIES_ERROR\x10\f\x12!\n" +
	"\x1dRPC_STATUS_UNAUTHORIZED_ERROR\x10\r\x12\x1c\n" +
	"\x18RPC_STATUS_PARSING_ERROR\x10\x0e\x12\x1c\n" +
	"\x18RPC_STATUS_ACCESS_DENIED\x10\x0f\x12\x1f\n" +
	"\x1bRPC_STATUS_ACCESS_SUSPENDED\x10\x10\x12\"\n" +
	"\x1eRPC_STATUS_DEVICE_INCOMPATIBLE\x10\x11\x12\"\n" +
	"\x1eRPC_STATUS_ACCESS_RATE_LIMITED\x10\x12\x12$\n" +
	" RPC_STATUS_GOOGLE_PLAY_NOT_READY\x10\x13\x12\x1f\n" +
	"\x1bRPC_STATUS_LOGIN_ERROR_BAIL\x10\x14\x12&\n" +
	"\"RPC_STATUS_MITM_DISALLOWED_REQUEST\x10cb\x06proto3"

var (
	file_rotom_proto_rawDescOnce sync.Once
	file_rotom_proto_rawDescData []byte
)

func file_rotom_proto_rawDescGZIP() []byte {
	file_rotom_proto_rawDescOnce.Do(func() {
		file_rotom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rotom_proto_rawDesc), len(file_rotom_proto_rawDesc)))
	})
	return file_rotom_proto_rawDescData
}

var file_rotom_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_rotom_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rotom_proto_goTypes = []any{
	(AuthStatus)(0),                           // 0: RotomProtos.AuthStatus
	(RpcStatus)(0),                            // 1: RotomProtos.RpcStatus
	(MitmRequest_Method)(0),                   // 2: RotomProtos.MitmRequest.Method
	(MitmRequest_LoginRequest_LoginSource)(0), // 3: RotomProtos.MitmRequest.LoginRequest.LoginSource
	(MitmResponse_Status)(0),                  // 4: RotomProtos.MitmResponse.Status
	(WelcomeMessage_Platform)(0),              // 5: RotomProtos.WelcomeMessage.Platform
	(RegisterControllerResponse_RegisterControllerResponseStatus)(0), // 6: RotomProtos.RegisterControllerResponse.RegisterControllerResponseStatus
	(*MitmRequest)(nil),                                // 7: RotomProtos.MitmRequest
	(*MitmResponse)(nil),                               // 8: RotomProtos.MitmResponse
	(*WelcomeMessage)(nil),                             // 9: RotomProtos.WelcomeMessage
	(*RegisterControllerRequest)(nil),                  // 10: RotomProtos.RegisterControllerRequest
	(*RegisterControllerResponse)(nil),                 // 11: RotomProtos.RegisterControllerResponse
	(*MitmRequest_LoginRequest)(nil),                   // 12: RotomProtos.MitmRequest.LoginRequest
	(*MitmRequest_RpcRequest)(nil),                     // 13: RotomProtos.MitmRequest.RpcRequest
	(*MitmRequest_RpcRequest_SingleRpcRequest)(nil),    // 14: RotomProtos.MitmRequest.RpcRequest.SingleRpcRequest
	(*MitmResponse_LoginResponse)(nil),                 // 15: RotomProtos.MitmResponse.LoginResponse
	(*MitmResponse_RpcResponse)(nil),                   // 16: RotomProtos.MitmResponse.RpcResponse
	(*MitmResponse_RpcResponse_SingleRpcResponse)(nil), // 17: RotomProtos.MitmResponse.RpcResponse.SingleRpcResponse
}
var file_rotom_proto_depIdxs = []int32{
	2,  // 0: RotomProtos.MitmRequest.method:type_name -> RotomProtos.MitmRequest.Method
	12, // 1: RotomProtos.MitmRequest.login_request:type_name -> RotomProtos.MitmRequest.LoginRequest
	13, // 2: RotomProtos.MitmRequest.rpc_request:type_name -> RotomProtos.MitmRequest.RpcRequest
	4,  // 3: RotomProtos.MitmResponse.status:type_name -> RotomProtos.MitmResponse.Status
	15, // 4: RotomProtos.MitmResponse.login_response:type_name -> RotomProtos.MitmResponse.LoginResponse
	16, // 5: RotomProtos.MitmResponse.rpc_response:type_name -> RotomProtos.MitmResponse.RpcResponse
	5,  // 6: RotomProtos.WelcomeMessage.platform:type_name -> RotomProtos.WelcomeMessage.Platform
	6,  // 7: RotomProtos.RegisterControllerResponse.status:type_name -> RotomProtos.RegisterControllerResponse.RegisterControllerResponseStatus
	3,  // 8: RotomProtos.MitmRequest.LoginRequest.source:type_name -> RotomProtos.MitmRequest.LoginRequest.LoginSource
	14, // 9: RotomProtos.MitmRequest.RpcRequest.request:type_name -> RotomProtos.MitmRequest.RpcRequest.SingleRpcRequest
	0,  // 10: RotomProtos.MitmResponse.LoginResponse.status:type_name -> RotomProtos.AuthStatus
	1,  // 11: RotomProtos.MitmResponse.RpcResponse.rpc_status:type_name -> RotomProtos.RpcStatus
	17, // 12: RotomProtos.MitmResponse.RpcResponse.response:type_name -> RotomProtos.MitmResponse.RpcResponse.SingleRpcResponse
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_rotom_proto_init() }
func file_rotom_proto_init() {
	if File_rotom_proto != nil {
		return
	}
	file_rotom_proto_msgTypes[0].OneofWrappers = []any{
		(*MitmRequest_LoginRequest_)(nil),
		(*MitmRequest_RpcRequest_)(nil),
	}
	file_rotom_proto_msgTypes[1].OneofWrappers = []any{
		(*MitmResponse_LoginResponse_)(nil),
		(*MitmResponse_RpcResponse_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rotom_proto_rawDesc), len(file_rotom_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rotom_proto_goTypes,
		DependencyIndexes: file_rotom_proto_depIdxs,
		EnumInfos:         file_rotom_proto_enumTypes,
		MessageInfos:      file_rotom_proto_msgTypes,
	}.Build()
	File_rotom_proto = out.File
	file_rotom_proto_goTypes = nil
	file_rotom_proto_depIdxs = nil
}
